version: "3.4"

services:
  pypi:
    image: pypiserver/pypiserver:latest
    command: "-o -P /data/auth/.htpasswd /data/packages"
    volumes:
      - pypi_packages:/data/packages
      - ${INFRA_DIR}/config/pypi/auth:/data/auth
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        traefik.enable: "true"
        traefik.port: 8080
        traefik.frontend.rule: "Host:pypi.${INFRA_DOMAIN}"

volumes:
  pypi_packages:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/pypi/packages"
